#cloud-config
users:
  - name: ansible
    ssh-authorized-keys:
     - ssh-rsa PUT IN A KEY
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash

packages:
  - sl

# manually set BOOTPROTO for static IP
# older cloud-config binary has bug?
runcmd:
  - [ sh, -c, 'sed -i s/BOOTPROTO=dhcp/BOOTPROTO=static/ /etc/sysconfig/network-scripts/ifcfg-ens192' ]

power_state:
  timeout: 30
  message: cya
  mode: reboot